export default {
  UPSERT_OVERDUE_TASK: 'UPSERT_OVERDUE_TASK',
  UPSERT_OVERDUE_TASKS: 'UPSERT_OVERDUE_TASKS',
  REFRESH_OVERDUE_TASKS: 'REFRESH_OVERDUE_TASKS',
  ASYNC_UPSERT_OVERDUE_TASKS: 'ASYNC_UPSERT_OVERDUE_TASKS',
  ASYNC_UPSERT_OVERDUE_TASK: 'ASYNC_UPSERT_OVERDUE_TASK',
};
